import React from 'react';
import { AbsoluteFill } from 'remotion';

export interface ThumbnailStillProps {
  /** Date in MM/DD format */
  date?: string;
  /** Day of week in Japanese (e.g. 月曜日) */
  dayOfWeek?: string;
  /** Slot label: 朝のニュース / 昼のニュース / 夜のニュース */
  slotLabel?: string;
  /** News headline (full) */
  headline: string;
  /** Short headline for thumbnail (10 chars max, generated by LLM) */
  thumbnailTitle?: string;
  /** Background image URL (first explain scene image) */
  backgroundImage?: string;
}

const SLOT_CONFIG: Record<string, { neon: string; glow: string; icon: string }> = {
  '朝のニュース': { neon: '#FF6B00', glow: 'rgba(255,107,0,0.6)', icon: '☀️' },
  '昼のニュース': { neon: '#00D4FF', glow: 'rgba(0,212,255,0.6)', icon: '🔆' },
  '夜のニュース': { neon: '#BF40FF', glow: 'rgba(191,64,255,0.6)', icon: '🌙' },
};

export const ThumbnailStill: React.FC<ThumbnailStillProps> = ({
  date,
  dayOfWeek,
  slotLabel = '朝のニュース',
  headline,
  thumbnailTitle,
  backgroundImage,
}) => {
  const slot = SLOT_CONFIG[slotLabel] ?? SLOT_CONFIG['朝のニュース'];
  const displayTitle = thumbnailTitle || headline;

  return (
    <AbsoluteFill
      style={{
        backgroundColor: '#0A0A1A',
        fontFamily: "'Hiragino Kaku Gothic StdN', sans-serif",
      }}
    >
      {/* Background image — bright, minimal overlay */}
      {backgroundImage && (
        <AbsoluteFill>
          <img
            src={backgroundImage}
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'cover',
            }}
          />
          {/* Minimal uniform overlay — 5% opacity */}
          <AbsoluteFill
            style={{
              backgroundColor: 'rgba(10,10,30,0.05)',
            }}
          />
        </AbsoluteFill>
      )}

      {/* Decorative neon line — top */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          height: 6,
          background: `linear-gradient(90deg, transparent 0%, ${slot.neon} 30%, ${slot.neon} 70%, transparent 100%)`,
          boxShadow: `0 0 30px ${slot.glow}, 0 0 60px ${slot.glow}`,
        }}
      />

      {/* Content layer — centered */}
      <AbsoluteFill
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          padding: 64,
        }}
      >
        {/* Semi-transparent backdrop behind text content */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 36,
            backgroundColor: 'rgba(10,10,30,0.20)',
            borderRadius: 40,
            paddingTop: 56,
            paddingBottom: 56,
            paddingLeft: 48,
            paddingRight: 48,
            width: '100%',
          }}
        >
          {/* Slot label — neon pill */}
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 20,
              backgroundColor: slot.neon,
              paddingTop: 24,
              paddingBottom: 24,
              paddingLeft: 44,
              paddingRight: 48,
              borderRadius: 60,
              boxShadow: `0 0 30px ${slot.glow}, 0 4px 20px rgba(0,0,0,0.3)`,
            }}
          >
            <span style={{ fontSize: 68 }}>{slot.icon}</span>
            <span
              style={{
                fontWeight: 900,
                fontSize: 68,
                color: '#FFFFFF',
                letterSpacing: 6,
                textShadow: '0 2px 8px rgba(0,0,0,0.4)',
              }}
            >
              {slotLabel}
            </span>
          </div>

          {/* Date badge — neon-bordered, centered */}
          {date && (
            <div
              style={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
                gap: 20,
                border: `4px solid ${slot.neon}`,
                borderRadius: 24,
                paddingTop: 20,
                paddingBottom: 18,
                paddingLeft: 44,
                paddingRight: 44,
                boxShadow: `0 0 20px ${slot.glow}, inset 0 0 15px rgba(0,0,0,0.3)`,
                backgroundColor: 'rgba(10,10,30,0.55)',
              }}
            >
              <span
                style={{
                  fontWeight: 900,
                  fontSize: 100,
                  color: '#FFFFFF',
                  lineHeight: 1.0,
                  letterSpacing: -1,
                }}
              >
                {date}
              </span>
              {dayOfWeek && (
                <span
                  style={{
                    fontWeight: 800,
                    fontSize: 64,
                    color: slot.neon,
                    lineHeight: 1.0,
                    letterSpacing: 4,
                    textShadow: `0 0 10px ${slot.glow}`,
                  }}
                >
                  {dayOfWeek}
                </span>
              )}
            </div>
          )}

          {/* Headline — centered */}
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: 16,
            }}
          >
            <span
              style={{
                fontWeight: 900,
                fontSize: 88,
                color: '#FFFFFF',
                lineHeight: 1.4,
                letterSpacing: 2,
                textAlign: 'center',
                textShadow: `0 4px 20px rgba(0,0,0,0.8), 0 0 8px ${slot.glow.replace('0.6', '0.25')}`,
                overflowWrap: 'break-word',
                wordBreak: 'keep-all',
              }}
            >
              {displayTitle}
            </span>
            {/* Neon accent bar under headline */}
            <div
              style={{
                width: 200,
                height: 5,
                borderRadius: 3,
                backgroundColor: slot.neon,
                boxShadow: `0 0 16px ${slot.glow}`,
              }}
            />
          </div>
        </div>
      </AbsoluteFill>

      {/* Decorative neon line — bottom */}
      <div
        style={{
          position: 'absolute',
          bottom: 0,
          left: 0,
          right: 0,
          height: 4,
          background: `linear-gradient(90deg, transparent 0%, ${slot.neon}80 40%, ${slot.neon}80 60%, transparent 100%)`,
          boxShadow: `0 0 20px ${slot.glow}`,
        }}
      />
    </AbsoluteFill>
  );
};
