import { resolve, join, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import fsExtra from 'fs-extra';
const { pathExists } = fsExtra;
import { createLogger } from '../utils/logger.js';

const log = createLogger('thumbnail');

/**
 * Extract a single frame from a video as a thumbnail (legacy fallback).
 */
export async function extractThumbnail(
  videoPath: string,
  outputPath: string,
  timestampSeconds?: number,
): Promise<void> {
  const { getFFmpegCommand, runFFmpeg } = await import('./ffmpeg.js');
  const timestamp = timestampSeconds ?? 2;
  log.info('Extracting thumbnail', { video: videoPath, timestamp });

  const command = getFFmpegCommand(videoPath)
    .seekInput(timestamp)
    .frames(1)
    .output(outputPath);

  await runFFmpeg(command);
}

export interface ThumbnailOptions {
  /** Date in MM/DD format */
  date?: string;
  /** Day of week (e.g. 月曜日) */
  dayOfWeek?: string;
  /** Slot: morning / noon / evening */
  slot?: string;
  /** News headline (full) */
  headline: string;
  /** Short headline for thumbnail (max ~10 chars, generated by LLM) */
  thumbnailTitle?: string;
  /** Path to background image (first explain scene image) */
  backgroundImagePath?: string;
}

const SLOT_LABEL_MAP: Record<string, string> = {
  morning: '朝のニュース',
  noon: '昼のニュース',
  evening: '夜のニュース',
};

/**
 * Render a branded thumbnail using Remotion's Still composition.
 */
export async function renderThumbnail(
  outputPath: string,
  options: ThumbnailOptions,
): Promise<void> {
  log.info('Rendering branded thumbnail', {
    headline: options.headline.slice(0, 30),
    slot: options.slot,
  });

  try {
    const { bundle } = await import('@remotion/bundler');
    const { renderStill, selectComposition } = await import('@remotion/renderer');
    const { link, copyFile, mkdir } = await import('node:fs/promises');

    const __filename = fileURLToPath(import.meta.url);
    const __dirname = dirname(__filename);
    const entryPoint = resolve(__dirname, '../../src/render/root.tsx');

    const bundleLocation = await bundle({
      entryPoint,
      webpackOverride: (config) => ({
        ...config,
        resolve: {
          ...config.resolve,
          extensionAlias: {
            '.js': ['.tsx', '.ts', '.jsx', '.js'],
          },
        },
      }),
    });

    // Link background image into bundle's public dir if available
    const bundlePublicDir = join(bundleLocation, 'public');
    await mkdir(bundlePublicDir, { recursive: true });

    let backgroundImage: string | undefined;
    if (options.backgroundImagePath && await pathExists(options.backgroundImagePath)) {
      const filename = basename(options.backgroundImagePath);
      const dest = join(bundlePublicDir, filename);
      try {
        await link(options.backgroundImagePath, dest);
      } catch {
        await copyFile(options.backgroundImagePath, dest);
      }
      backgroundImage = `/public/${filename}`;
    }

    const slotLabel = options.slot ? SLOT_LABEL_MAP[options.slot] ?? '朝のニュース' : '朝のニュース';

    const inputProps = {
      date: options.date,
      dayOfWeek: options.dayOfWeek,
      slotLabel,
      headline: options.headline,
      thumbnailTitle: options.thumbnailTitle,
      backgroundImage,
    };

    const composition = await selectComposition({
      serveUrl: bundleLocation,
      id: 'Thumbnail',
      inputProps,
    });

    await renderStill({
      composition,
      serveUrl: bundleLocation,
      output: outputPath,
      inputProps,
    });

    log.info('Branded thumbnail rendered', { output: outputPath });
  } catch (err) {
    log.warn('Branded thumbnail render failed, falling back to placeholder', {
      error: String(err),
    });
    // Fallback: skip branded thumbnail (video frame extraction happens separately)
  }
}
